apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o router-api
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: router-api
  name: router-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: router-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o router-api
        kompose.version: 1.28.0 (c4137012e)
      labels:
        org: routing-system
        class: router-api
        app.kubernetes.io/name: router-api
        io.kompose.service: router-api
    spec:
      containers:
        - image: fontyssa/router-api
          name: router-api
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{.Values.resources.memory | quote }}
              cpu: {{.Values.resources.cpu | quote }}
      restartPolicy: Always
