apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: "default-pool"
  namespace: metallb-system
spec:
  addresses:
    - 172.42.0.200-172.42.0.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-ip
  namespace: metallb-system