apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mysql-config-paymentrr
  name: mysql-config-paymentrr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
