apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o payment-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: paymentmysql
  name: paymentmysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: paymentmysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o payment-service
        kompose.version: 1.28.0 (c4137012e)
      labels:
        org: routing-system
        class: paymentmysql
        app.kubernetes.io/name: paymentmysql
        io.kompose.service: paymentmysql
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
          image: mysql
          name: paymentmysql
          ports:
            - containerPort: 3306
          resources:
            requests:
              memory: {{.Values.resources.dbMemory | quote }}
              cpu: {{.Values.resources.dbCpu | quote }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data-paymentrr
            - mountPath: /etc/mysql/conf.d
              name: mysql-config-paymentrr
      restartPolicy: Always
      volumes:
        - name: mysql-data-paymentrr
          persistentVolumeClaim:
            claimName: mysql-data-paymentrr
        - name: mysql-config-paymentrr
          persistentVolumeClaim:
            claimName: mysql-config-paymentrr
