apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o international-api
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: international-api
  name: international-api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: international-api
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o international-api
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.service: international-api
    spec:
      containers:
        - image: fontyssa/international-api
          name: international-api
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{.Values.resources.memory | quote }}
              cpu: {{.Values.resources.cpu | quote }}
      restartPolicy: Always
      dnsPolicy: ClusterFirst
