apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o international-api
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: international-api
  name: international-api
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: international-api
