/*
 * Rekeningrijden Belgium API
 *
 * The international API for Rekeningrijden Belgium
 *
 * OpenAPI spec version: 0.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using IO.Swagger.Attributes;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers;

/// <summary>
/// 
/// </summary>
[ApiController]
[Route("[controller]")]
public class InterpolApiController : ControllerBase
{ 
    /// <summary>
    /// Report stolen vehicle location
    /// </summary>
    /// <remarks>Report the location of a stolen vehicle and the data needed to recognize the vehicle</remarks>
    /// <param name="body"></param>
    /// <param name="cc">ISO 3166-1 Alpha-2 compliant country code</param>
    /// <response code="200">acknowledged</response>
    /// <response code="400">bad input</response>
    [HttpPost]
    [Route("/report")]
    [ValidateModelState]
    [SwaggerOperation("CarReported")]
    public async Task<IActionResult> CarReported([FromBody]StolenVehicle body, [FromQuery][Required()][RegularExpression("/[A-Z]{2}/")]string cc)
    { 
        //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
        return Ok();

        //TODO: Uncomment the next line to return response 400 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
        // return StatusCode(400);
    }
}