/*
 * Rekeningrijden Belgium API
 *
 * The international API for Rekeningrijden Belgium
 *
 * OpenAPI spec version: 0.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Text;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models;

/// <summary>
/// An OSM Node
/// </summary>
[DataContract]
public partial class Node : IEquatable<Node>
{ 
    /// <summary>
    /// Gets or Sets Id
    /// </summary>

    [DataMember(Name="id")]
    public string? Id { get; set; }

    /// <summary>
    /// Gets or Sets Lat
    /// </summary>

    [DataMember(Name="lat")]
    public float? Lat { get; set; }

    /// <summary>
    /// Gets or Sets Lon
    /// </summary>

    [DataMember(Name="lon")]
    public float? Lon { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class Node {\n");
        sb.Append("  Id: ").Append(Id).Append("\n");
        sb.Append("  Lat: ").Append(Lat).Append("\n");
        sb.Append("  Lon: ").Append(Lon).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        return obj.GetType() == GetType() && Equals((Node)obj);
    }

    /// <summary>
    /// Returns true if Node instances are equal
    /// </summary>
    /// <param name="other">Instance of Node to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(Node other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;

        return 
            (
                Id == other.Id ||
                Id != null &&
                Id.Equals(other.Id)
            ) && 
            (
                Lat == other.Lat ||
                Lat != null &&
                Lat.Equals(other.Lat)
            ) && 
            (
                Lon == other.Lon ||
                Lon != null &&
                Lon.Equals(other.Lon)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            // Suitable nullity checks etc, of course :)
            if (Id != null)
                hashCode = hashCode * 59 + Id.GetHashCode();
            if (Lat != null)
                hashCode = hashCode * 59 + Lat.GetHashCode();
            if (Lon != null)
                hashCode = hashCode * 59 + Lon.GetHashCode();
            return hashCode;
        }
    }

    #region Operators
#pragma warning disable 1591

    public static bool operator ==(Node left, Node right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(Node left, Node right)
    {
        return !Equals(left, right);
    }

#pragma warning restore 1591
    #endregion Operators
}