/*
 * Rekeningrijden Belgium API
 *
 * The international API for Rekeningrijden Belgium
 *
 * OpenAPI spec version: 0.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models;

/// <summary>
/// A calculated route with vehicle identifier, total price and a series of OSM nodes and segment prices.
/// </summary>
[DataContract]
public partial class Route : IEquatable<Route>, IRoute
{ 
    /// <summary>
    /// The ID of the vehicle in the vehicle&#x27;s country of origin&#x27;s system
    /// </summary>
    /// <value>The ID of the vehicle in the vehicle&#x27;s country of origin&#x27;s system</value>

    [DataMember(Name="id")]
    public Guid? Id { get; set; }

    /// <summary>
    /// Gets or Sets PriceTotal
    /// </summary>

    [DataMember(Name="priceTotal")]
    public decimal? PriceTotal { get; set; }

    /// <summary>
    /// Gets or Sets Segments
    /// </summary>

    [DataMember(Name="segments")]
    public List<Segment> Segments { get; set; }

    /// <summary>
    /// Returns the string presentation of the object
    /// </summary>
    /// <returns>String presentation of the object</returns>
    public override string ToString()
    {
        var sb = new StringBuilder();
        sb.Append("class Route {\n");
        sb.Append("  Id: ").Append(Id).Append("\n");
        sb.Append("  PriceTotal: ").Append(PriceTotal).Append("\n");
        sb.Append("  Segments: ").Append(Segments).Append("\n");
        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>
    /// Returns the JSON string presentation of the object
    /// </summary>
    /// <returns>JSON string presentation of the object</returns>
    public string ToJson()
    {
        return JsonConvert.SerializeObject(this, Formatting.Indented);
    }

    /// <summary>
    /// Returns true if objects are equal
    /// </summary>
    /// <param name="obj">Object to be compared</param>
    /// <returns>Boolean</returns>
    public override bool Equals(object obj)
    {
        if (ReferenceEquals(null, obj)) return false;
        if (ReferenceEquals(this, obj)) return true;
        return obj.GetType() == GetType() && Equals((Route)obj);
    }

    /// <summary>
    /// Returns true if Route instances are equal
    /// </summary>
    /// <param name="other">Instance of Route to be compared</param>
    /// <returns>Boolean</returns>
    public bool Equals(Route other)
    {
        if (ReferenceEquals(null, other)) return false;
        if (ReferenceEquals(this, other)) return true;

        return 
            (
                Id == other.Id ||
                Id != null &&
                Id.Equals(other.Id)
            ) && 
            (
                PriceTotal == other.PriceTotal ||
                PriceTotal != null &&
                PriceTotal.Equals(other.PriceTotal)
            ) && 
            (
                Segments == other.Segments ||
                Segments != null &&
                Segments.SequenceEqual(other.Segments)
            );
    }

    /// <summary>
    /// Gets the hash code
    /// </summary>
    /// <returns>Hash code</returns>
    public override int GetHashCode()
    {
        unchecked // Overflow is fine, just wrap
        {
            var hashCode = 41;
            // Suitable nullity checks etc, of course :)
            if (Id != null)
                hashCode = hashCode * 59 + Id.GetHashCode();
            if (PriceTotal != null)
                hashCode = hashCode * 59 + PriceTotal.GetHashCode();
            if (Segments != null)
                hashCode = hashCode * 59 + Segments.GetHashCode();
            return hashCode;
        }
    }

    #region Operators
#pragma warning disable 1591

    public static bool operator ==(Route left, Route right)
    {
        return Equals(left, right);
    }

    public static bool operator !=(Route left, Route right)
    {
        return !Equals(left, right);
    }

#pragma warning restore 1591
    #endregion Operators
}