/*
 * Rekeningrijden Belgium API
 *
 * The international API for Rekeningrijden Belgium
 *
 * OpenAPI spec version: 0.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models;

/// <summary>
/// A vehicle's EU standard classification
/// </summary>
/// <value>A vehicle's EU standard classification</value>
[JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
public enum VehicleClassification
{
    /// <summary>
    /// Enum LEnum for L
    /// </summary>
    [EnumMember(Value = "L")]
    L = 0,
    /// <summary>
    /// Enum L1Enum for L1
    /// </summary>
    [EnumMember(Value = "L1")]
    L1 = 1,
    /// <summary>
    /// Enum L2Enum for L2
    /// </summary>
    [EnumMember(Value = "L2")]
    L2 = 2,
    /// <summary>
    /// Enum L3Enum for L3
    /// </summary>
    [EnumMember(Value = "L3")]
    L3 = 3,
    /// <summary>
    /// Enum L4Enum for L4
    /// </summary>
    [EnumMember(Value = "L4")]
    L4 = 4,
    /// <summary>
    /// Enum L5Enum for L5
    /// </summary>
    [EnumMember(Value = "L5")]
    L5 = 5,
    /// <summary>
    /// Enum L6Enum for L6
    /// </summary>
    [EnumMember(Value = "L6")]
    L6 = 6,
    /// <summary>
    /// Enum L7Enum for L7
    /// </summary>
    [EnumMember(Value = "L7")]
    L7 = 7,
    /// <summary>
    /// Enum MEnum for M
    /// </summary>
    [EnumMember(Value = "M")]
    M = 8,
    /// <summary>
    /// Enum M1Enum for M1
    /// </summary>
    [EnumMember(Value = "M1")]
    M1 = 9,
    /// <summary>
    /// Enum M2Enum for M2
    /// </summary>
    [EnumMember(Value = "M2")]
    M2 = 10,
    /// <summary>
    /// Enum M3Enum for M3
    /// </summary>
    [EnumMember(Value = "M3")]
    M3 = 11,
    /// <summary>
    /// Enum NEnum for N
    /// </summary>
    [EnumMember(Value = "N")]
    N = 12,
    /// <summary>
    /// Enum N1Enum for N1
    /// </summary>
    [EnumMember(Value = "N1")]
    N1 = 13,
    /// <summary>
    /// Enum N2Enum for N2
    /// </summary>
    [EnumMember(Value = "N2")]
    N2 = 14,
    /// <summary>
    /// Enum N3Enum for N3
    /// </summary>
    [EnumMember(Value = "N3")]
    N3 = 15,
    /// <summary>
    /// Enum OEnum for O
    /// </summary>
    [EnumMember(Value = "O")]
    O = 16,
    /// <summary>
    /// Enum O1Enum for O1
    /// </summary>
    [EnumMember(Value = "O1")]
    O1 = 17,
    /// <summary>
    /// Enum O2Enum for O2
    /// </summary>
    [EnumMember(Value = "O2")]
    O2 = 18,
    /// <summary>
    /// Enum O3Enum for O3
    /// </summary>
    [EnumMember(Value = "O3")]
    O3 = 19,
    /// <summary>
    /// Enum O4Enum for O4
    /// </summary>
    [EnumMember(Value = "O4")]
    O4 = 20,
    /// <summary>
    /// Enum TEnum for T
    /// </summary>
    [EnumMember(Value = "T")]
    T = 21,
    /// <summary>
    /// Enum REnum for R
    /// </summary>
    [EnumMember(Value = "R")]
    R = 22,
    /// <summary>
    /// Enum SEnum for S
    /// </summary>
    [EnumMember(Value = "S")]
    S = 23,
    /// <summary>
    /// Enum GEnum for G
    /// </summary>
    [EnumMember(Value = "G")]
    G = 24          }