---
trigger:
  branches:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

variables:
  # Differentiate between branches
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
  # Configure SonarCloud
  cliProjectKey: FontysVerkeer_Rekeningrijden
  cliProjectName: Rekeningrijden

resources:
  repositories:
    - repository: templates
      endpoint: Groep2Rekeningrijden
      type: github
      name: Groep2Rekeningrijden/Templates

stages:
  - stage: test_isolated
    jobs:
      # --- Run linters on isolated environment ---
      - job: linting
        steps:
          - template: install/python-3_11.yml@templates
          - template: lint/python.yml@templates
          - template: lint/fail_if_linters_fail.yml@templates

      # --- Run unit tests on isolated instance ---
      - job: unit_test
        steps:
          - checkout: self
            fetchDepth: 0
          - template: install/python-3_11.yml@templates
          - template: test/sonar_cloud_prepare.yml@templates
          - template: test/python_pytest.yml@templates
          - template: test/sonar_cloud_analyze.yml@templates

  # --- Run tests on dev environment ---
  - stage: test_dev
    dependsOn: test_isolated
    condition: and(succeeded(), or(eq(variables.isDev, 'true'), eq(variables.isMain, 'true')))
    jobs:
      - job: B1
      - job: B2

  # --- Deploy to prod ---
  - stage: prod
    dependsOn: test_dev
    condition: and(succeeded(), eq(variables.isMain, 'true'))
    jobs:
      - job: C1
      - job: C2
