// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentService.Data;

#nullable disable

namespace PaymentService.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230531092116_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PaymentService.Models.PricingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("PriceTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ValueDescription")
                        .HasColumnType("double");

                    b.Property<string>("ValueName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pricing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("954fe08c-032b-411b-8a62-3f3b687f0e30"),
                            PriceTitle = "highway",
                            PriceType = "modifier",
                            ValueDescription = 1.25,
                            ValueName = "primary"
                        },
                        new
                        {
                            Id = new Guid("77f23aa5-ba42-46e5-b071-427acbd692df"),
                            PriceTitle = "highway",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "secondary"
                        },
                        new
                        {
                            Id = new Guid("2cae3bdb-e585-47d2-bedc-3b38f38c104d"),
                            PriceTitle = "highway",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "tertiary"
                        },
                        new
                        {
                            Id = new Guid("bdf1c2df-31b4-4068-8a57-382201013e76"),
                            PriceTitle = "highway",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "residential"
                        },
                        new
                        {
                            Id = new Guid("a71f3a9c-7fb7-4fe9-989d-0902efe9bfdc"),
                            PriceTitle = "boundary",
                            PriceType = "modifier",
                            ValueDescription = 1.05,
                            ValueName = "suburb"
                        },
                        new
                        {
                            Id = new Guid("19a96643-4227-4f17-b742-1bd2372a0eb6"),
                            PriceTitle = "boundary",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "tertiary"
                        },
                        new
                        {
                            Id = new Guid("a0e3b01a-793f-4204-ab41-73e6509619a2"),
                            PriceTitle = "boundary",
                            PriceType = "modifier",
                            ValueDescription = 1.05,
                            ValueName = "administrative"
                        },
                        new
                        {
                            Id = new Guid("658b15e7-fae4-480a-bfea-b550f1a6e4a0"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "L"
                        },
                        new
                        {
                            Id = new Guid("afbf2564-bd36-4339-ac0c-5acc337cb3d7"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1499999999999999,
                            ValueName = "L1"
                        },
                        new
                        {
                            Id = new Guid("f7f365dc-8fd2-4395-a6fa-3aff345a1b89"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "L2"
                        },
                        new
                        {
                            Id = new Guid("b4eedf22-c6ae-45a8-96b3-683869edf5a2"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.25,
                            ValueName = "L3"
                        },
                        new
                        {
                            Id = new Guid("fb92ae6d-2fb2-4f98-94cc-d9950cc6307c"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.3,
                            ValueName = "L4"
                        },
                        new
                        {
                            Id = new Guid("91e556ac-49a0-4a0c-b796-71eac1b19db7"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.3500000000000001,
                            ValueName = "L5"
                        },
                        new
                        {
                            Id = new Guid("b9777bb2-c9dd-4634-a4e8-9f2ee6f4f2d6"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.3999999999999999,
                            ValueName = "L6"
                        },
                        new
                        {
                            Id = new Guid("8c19a10a-9b90-4d07-8047-5ada8319dcb3"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "M"
                        },
                        new
                        {
                            Id = new Guid("3b333747-c307-4354-92e0-e857d2ed1f65"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1499999999999999,
                            ValueName = "M1"
                        },
                        new
                        {
                            Id = new Guid("552c09b1-4fa3-4cfd-b1d5-860887584f80"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "M2"
                        },
                        new
                        {
                            Id = new Guid("12caf2cb-5134-4840-a9ce-fc0d66b5d492"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.25,
                            ValueName = "M3"
                        },
                        new
                        {
                            Id = new Guid("0883a3cb-51fb-48f3-b9a4-c7c66437b935"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "N"
                        },
                        new
                        {
                            Id = new Guid("b555e1de-ea94-4b05-b255-5ef630535d07"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1499999999999999,
                            ValueName = "N1"
                        },
                        new
                        {
                            Id = new Guid("08744e09-bc13-4d36-9fd7-1a2872a4c8ea"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "N2"
                        },
                        new
                        {
                            Id = new Guid("280bdbe2-930f-4db1-a3a6-edd7dbd48318"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.25,
                            ValueName = "N3"
                        },
                        new
                        {
                            Id = new Guid("58eb1118-e434-4905-8bba-d1b896a932d8"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "O"
                        },
                        new
                        {
                            Id = new Guid("94167264-a926-49fc-9e17-def1d4843a26"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1499999999999999,
                            ValueName = "O1"
                        },
                        new
                        {
                            Id = new Guid("6a2da48a-322d-48c3-a536-6904ba4fb031"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "O2"
                        },
                        new
                        {
                            Id = new Guid("d917c25f-a947-4c51-8f2f-88c80116fa5e"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.25,
                            ValueName = "O3"
                        },
                        new
                        {
                            Id = new Guid("92e23192-6b44-48a4-b006-b6724ff8a4fc"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.25,
                            ValueName = "O4"
                        },
                        new
                        {
                            Id = new Guid("971de403-4d02-4165-80f7-5d9b275db6a9"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "T"
                        },
                        new
                        {
                            Id = new Guid("8b61c8da-bb12-4684-9c2f-c268a917b553"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "R"
                        },
                        new
                        {
                            Id = new Guid("b953e1b6-3848-4024-a888-be952294ab0b"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "S"
                        },
                        new
                        {
                            Id = new Guid("1328698f-6b2c-425a-a699-415260d18d70"),
                            PriceTitle = "vehicleClassification",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "G"
                        },
                        new
                        {
                            Id = new Guid("b957f434-8533-4efa-b1db-28266b496d7e"),
                            PriceTitle = "fuelType",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "Brandstof"
                        },
                        new
                        {
                            Id = new Guid("6f1f3859-57d4-42e7-bcb9-32b62487c2da"),
                            PriceTitle = "fuelType",
                            PriceType = "modifier",
                            ValueDescription = 1.1000000000000001,
                            ValueName = "Diesel"
                        },
                        new
                        {
                            Id = new Guid("a5c9ee75-9d55-4ac0-873f-dc7bd8144055"),
                            PriceTitle = "fuelType",
                            PriceType = "modifier",
                            ValueDescription = 1.05,
                            ValueName = "Elektriciteit"
                        },
                        new
                        {
                            Id = new Guid("3148778d-6c6d-46ec-82b9-5bb4f4f27d5f"),
                            PriceTitle = "rushPrice",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "7"
                        },
                        new
                        {
                            Id = new Guid("6d36fe48-463f-494d-bcb9-3f3ed3b47789"),
                            PriceTitle = "rushPrice",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "8"
                        },
                        new
                        {
                            Id = new Guid("c4882398-f89e-4016-ab95-08a35fc46aa7"),
                            PriceTitle = "rushPrice",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "16"
                        },
                        new
                        {
                            Id = new Guid("d039f5b4-1b24-46a5-b1d5-5bf2d57fdd71"),
                            PriceTitle = "rushPrice",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "17"
                        },
                        new
                        {
                            Id = new Guid("809d484a-e8ad-4c65-adbb-c5bc91ebc7e3"),
                            PriceTitle = "rushPrice",
                            PriceType = "modifier",
                            ValueDescription = 1.2,
                            ValueName = "18"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
