apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: {{.Values.serviceName}}-osmnx-cache
  name: {{.Values.serviceName}}-osmnx-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
