services:
  tracker-runner-brussels:
    image: fontyssa/tracker-runner
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - COUNT=1
      - INTERVAL=3
      - BATCH_SIZE=5
      - STATUS_INTERVAL=120
      - TIME_FACTOR=100
      - CAR_URL=https://car.oibss.nl/
      - TARGET_URL=https://tracker.oibss.nl/

  tracker-runner-nl-to-be:
    image: fontyssa/tracker-runner
    environment:
      - COUNT=1
      - INTERVAL=3
      - BATCH_SIZE=5
      - STATUS_INTERVAL=120
      - TIME_FACTOR=1
      - CAR_URL=https://car.oibss.nl/
      - TARGET_URL=https://international.oibss.nl/
      - INTERNATIONAL=true
      - CC=NL
      - ROUTES_SOURCE=/pregen/dutch_border_belgium_side

  tracker-runner-be-to-nl:
    image: fontyssa/tracker-runner
    environment:
      - COUNT=10
      - INTERVAL=3
      - BATCH_SIZE=5
      - STATUS_INTERVAL=120
      - TIME_FACTOR=1
      - CAR_URL=
      - TARGET_URL=
      - INTERNATIONAL=true
      - CC=BE
      - ROUTES_SOURCE=/pregen/dutch_border_dutch_side

  tracker-runner-lu-to-be:
    image: fontyssa/tracker-runner
    environment:
      - COUNT=10
      - INTERVAL=3
      - BATCH_SIZE=5
      - STATUS_INTERVAL=120
      - TIME_FACTOR=1
      - CAR_URL=
      - TARGET_URL=
      - INTERNATIONAL=true
      - CC=LU
      - ROUTES_SOURCE=/pregen/luxembourg_border_belgium_side

  tracker-runner-be-to-lu:
    image: fontyssa/tracker-runner
    environment:
      - COUNT=10
      - INTERVAL=3
      - BATCH_SIZE=5
      - STATUS_INTERVAL=120
      - TIME_FACTOR=1
      - CAR_URL=
      - TARGET_URL=
      - INTERNATIONAL=true
      - CC=BE
      - ROUTES_SOURCE=/pregen/luxembourg_border_luxembourg_side