apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o coordinate-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: coordinate-service
  name: coordinate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: coordinate-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o coordinate-service
        kompose.version: 1.28.0 (c4137012e)
      labels:
        org: routing-system
        class: coordinate-service
        app.kubernetes.io/name: coordinate-service
        io.kompose.service: coordinate-service
    spec:
      containers:
        - image: fontyssa/coordinate-service
          name: coordinate-service
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{.Values.resources.memory | quote }}
              cpu: {{.Values.resources.cpu | quote }}
      restartPolicy: Always
