apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o coordinate-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: coordinate-service
  name: coordinate-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: coordinate-service
