apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o coordinate-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: coordinate-service-mongo
  name: coordinate-service-mongo
spec:
  ports:
    - name: "27017"
      port: 27017
      targetPort: 27017
  selector:
    io.kompose.service: coordinate-service-mongo
