apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o data-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: data-service-mongo-express
  name: data-service-mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-service-mongo-express
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o data-service
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.service: data-service-mongo-express
    spec:
      containers:
        - env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: data-service-mongo
          image: mongo-express
          name: data-service-mongo-express
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: {{.Values.resources.dbMemory | quote }}
              cpu: {{.Values.resources.dbCpu | quote }}
      restartPolicy: Always
