apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o data-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: data-service-mongo
  name: data-service-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: data-service-mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c -f docker-compose.yml -o data-service
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.service: data-service-mongo
    spec:
      containers:
        - image: mongo
          name: data-service-mongo
          ports:
            - containerPort: 27017
          resources:
            requests:
              memory: {{.Values.resources.dbMemory | quote }}
              cpu: {{.Values.resources.dbCpu | quote }}
          volumeMounts:
            - mountPath: /data/db
              name: data-db-volume
      restartPolicy: Always
      volumes:
        - name: data-db-volume
          persistentVolumeClaim:
            claimName: data-db-volume
