apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml -o data-service
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: data-service-mongo-express
  name: data-service-mongo-express
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    io.kompose.service: data-service-mongo-express
