apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{.Values.serviceName}}-healthcheck
spec:
  healthCheck:
    checkIntervalSec: 15
    timeoutSec: 15
    healthyThreshold: 1
    unhealthyThreshold: 2
    type: HTTPS
    requestPath: /health
    port: 443