apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: paymentservice
          image: paymentservice
          imagePullPolicy: Never

