apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/part-of: rekeningrijden
  name: coordinate-service
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://groep2rekeningrijden.github.io/charts/
    chart: coordinate-service
    targetRevision: '*'
    helm:
      values: |
        resources:
          memory: 500Mi
          cpu: 500m
          dbMemory: 800Mi
          dbCpu: 750m
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
