apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://dl.gitea.io/charts
    chart: gitea
    targetRevision: '*'
    helm:
      values: |
        gitea:
          admin:
            username: gitea_admin
            password: admin
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
            nginx.ingress.kubernetes.io/ssl-redirect: 'false'
          className: nginx
          hosts:
            - host: gitea.kind.cluster
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: gitea.kind.cluster
              hosts:
                - gitea.kind.cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  revisionHistoryLimit: 3
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
    automated:
      prune: true
      selfHeal: true
