apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kwetter-web
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: kwetter
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://github.com/davidhellinga/kwetter-web-helm.git'
    targetRevision: '*'
    chart: kwetter-web
  sources: []
  project: default
  revisionHistoryLimit: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
      - FailOnSharedResource=true
      - PruneLast=true
      - Replace=true
