apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-sharded
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kwetter
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '*'
    chart: mongodb-sharded
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
