apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kwetter
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: '*'
    chart: rabbitmq-cluster-operator
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true

# TODO:
# https://www.rabbitmq.com/kubernetes/operator/quickstart-operator.html
# https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples/tls