apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: car-service
  name: car-service
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      io.kompose.service: car-service
  strategy: { }
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.28.0 (c4137012e)
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        org: routing-system
        class: car-service
        app.kubernetes.io/name: car-service
        io.kompose.network/carservice-default: "true"
        io.kompose.service: car-service
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: fontyssa/car-service
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            requests:
              memory: {{.Values.resources.memory | quote }}
              cpu: {{.Values.resources.cpu | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
              {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.affinity }}
      affinity:
              {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.tolerations }}
      tolerations:
              {{- toYaml . | nindent 8 }}
            {{- end }}

